import math
import random
import chess
import numpy as np
from board import board_to_input_planes
from typing import Dict, Optional, Callable, Tuple, List
import uuid

class AlphaZeroMoveIndexer:
    def __init__(self):
        # --- 1. Define Directions ---
        # Queen-like directions (0-7)
        self.queen_dirs = [
            (0, 1),   # North
            (1, 1),   # North-East
            (1, 0),   # East
            (1, -1),  # South-East
            (0, -1),  # South
            (-1, -1), # South-West
            (-1, 0),  # West
            (-1, 1)   # North-West
        ]
        
        # Knight jumps (0-7)
        self.knight_moves = [
            (1, 2), (2, 1), (2, -1), (1, -2),
            (-1, -2), (-2, -1), (-2, 1), (-1, 2)
        ]
        
        # Underpromotion pieces map (Index -> Piece)
        self.under_promo_pieces = [chess.KNIGHT, chess.BISHOP, chess.ROOK]
        
        # Underpromotion direction map (Index -> File Delta)
        # 0=Left(-1), 1=Forward(0), 2=Right(+1)
        self.under_promo_file_deltas = [-1, 0, 1]

        # --- 2. Pre-compute Forward Lookups (Move -> Plane) ---
        self.move_to_plane = {}
        
        # Queen Moves (Planes 0-55)
        count = 0
        for dx, dy in self.queen_dirs:
            for dist in range(1, 8):
                self.move_to_plane[(dx * dist, dy * dist)] = count
                count += 1
                
        # Knight Moves (Planes 56-63)
        for dx, dy in self.knight_moves:
            self.move_to_plane[(dx, dy)] = count
            count += 1

        # (Underpromotions 64-72 are handled procedurally in encode/decode)

    def decode(self, idx: int, board: chess.Board) -> chess.Move:
        """
        Decodes an integer index [0-4671] back into a chess.Move object.
        REQUIRES 'board' to determine if a move is a promotion (Queen vs Pawn).
        """
        # 1. Extract Source Square and Plane ID
        from_sq = idx // 73
        plane_id = idx % 73
        
        # Variables to determine destination
        to_sq = None
        promotion = None

        # --- Case A: Underpromotions (Planes 64-72) ---
        # These are EXPLICIT promotions to Knight, Bishop, or Rook.
        if plane_id >= 64:
            residue = plane_id - 64
            direction_idx = residue // 3  # 0=Left, 1=Forward, 2=Right
            piece_idx = residue % 3       # 0=Knight, 1=Bishop, 2=Rook
            
            # Determine File Delta (Left/-1, Forward/0, Right/+1)
            delta_file = self.under_promo_file_deltas[direction_idx]
            
            # Determine Rank Delta based on whose turn it is
            # (White promotes UP/+1, Black promotes DOWN/-1)
            color = board.color_at(from_sq)
            delta_rank = 1 if color == chess.WHITE else -1
            
            # Calculate To-Square
            from_file = chess.square_file(from_sq)
            from_rank = chess.square_rank(from_sq)
            
            to_file = from_file + delta_file
            to_rank = from_rank + delta_rank
            
            to_sq = chess.square(to_file, to_rank)
            promotion = self.under_promo_pieces[piece_idx]

        # --- Case B: Knight Moves (Planes 56-63) ---
        elif 56 <= plane_id < 64:
            k_idx = plane_id - 56
            dx, dy = self.knight_moves[k_idx]
            
            # Knight moves are absolute; just add delta
            # (Note: Need to handle boundary checks if the network outputs garbage,
            # but for valid indices, this arithmetic holds).
            to_sq = from_sq + (dy * 8) + dx
            
        # --- Case C: Queen/Regular Moves (Planes 0-55) ---
        else:
            direction_idx = plane_id // 7
            distance = (plane_id % 7) + 1
            
            dx_dir, dy_dir = self.queen_dirs[direction_idx]
            delta_x = dx_dir * distance
            delta_y = dy_dir * distance
            
            to_sq = from_sq + (delta_y * 8) + delta_x

        # --- Final Polish: Auto-Detect Queen Promotions ---
        # The planes 0-55 do not "know" they are promotions.
        # We must ask the board: "Is a PAWN moving to the LAST RANK?"
        
        # 1. Check if we have a valid calculated to_sq (within board limits)
        if not (0 <= to_sq < 64):
            return None # Invalid index/move generated by network

        # 2. If we haven't already assigned an underpromotion (N/B/R)...
        if promotion is None:
            piece = board.piece_at(from_sq)
            if piece and piece.piece_type == chess.PAWN:
                to_rank = chess.square_rank(to_sq)
                # If White Pawn hits Rank 7 (0-indexed) or Black Pawn hits Rank 0
                if (piece.color == chess.WHITE and to_rank == 7) or \
                   (piece.color == chess.BLACK and to_rank == 0):
                    promotion = chess.QUEEN

        return chess.Move(from_sq, to_sq, promotion)

    def encode(self, move: chess.Move) -> int:
        # ... (Same implementation as provided in previous answer) ...
        # Copied here briefly for completeness of the Class structure
        from_sq = move.from_square
        to_sq = move.to_square
        df = chess.square_file(to_sq) - chess.square_file(from_sq)
        dr = chess.square_rank(to_sq) - chess.square_rank(from_sq)
        
        if move.promotion and move.promotion != chess.QUEEN:
            p_idx = {chess.KNIGHT: 0, chess.BISHOP: 1, chess.ROOK: 2}[move.promotion]
            d_idx = { -1: 0, 0: 1, 1: 2 }[df]
            plane_idx = 64 + (d_idx * 3) + p_idx
        else:
            plane_idx = self.move_to_plane.get((df, dr))
            if plane_idx is None: return None
            
        return (from_sq * 73) + plane_idx

class MCTSNode:
    def __init__(self, board: chess.Board, parent: Optional["MCTSNode"]=None, parent_move: Optional[chess.Move]=None):
        self.board = board
        self.parent = parent
        self.parent_move = parent_move
        self.children: Dict[chess.Move, MCTSNode] = {}
        self.is_expanded = False

        # Node statistics
        self.N = 0          # visit count of this node
        self.W = 0.0        # total value (from perspective of player to move at this node)
        self.Q = 0.0        # mean value

        # Edge priors P(s,a): stored in parent.P[move]
        self.P: Dict[chess.Move, float] = {}  # only meaningful for nodes with children

PolicyValueFn = Callable[[chess.Board], Tuple[Dict[chess.Move, float], float]]


class MCTS:
    def __init__(self, c_puct: float = 1.5, n_simulations: int = 200, batch_size: int = 1,
                 inference_queue=None, inference_result_queue=None, worker_id: int = 0):
        self.c_puct = c_puct
        self.n_simulations = n_simulations
        self.batch_size = batch_size
        device = "cpu"
        self.device = device
        self.move_indexer = AlphaZeroMoveIndexer()
        self.inference_queue = inference_queue
        self.response_queue = inference_result_queue  # Now a dedicated Queue per worker
        self.worker_id = worker_id
        self.pending_inferences = {}  # request_id -> (pending_leaves, batch_tensor)

    def search(self, root_board: chess.Board) -> Tuple[Optional[chess.Move], Dict[chess.Move, float]]:
        root = MCTSNode(root_board.copy(stack=False)) # create new copy

        # Batched evaluation: collect leaves and evaluate in batches
        pending_leaves = []  # List of (leaf, path) tuples for non-terminal nodes

        for sim in range(self.n_simulations):
            leaf, path = self._select(root)

            if leaf.board.is_game_over():
                value = self._get_terminal_value(leaf.board)
                self._backpropagate(path, value)
                continue

            pending_leaves.append((leaf, path))

            # Evaluate batch when full or at end of simulations
            if len(pending_leaves) >= self.batch_size or sim == self.n_simulations - 1:
                if pending_leaves:
                    self._batch_evaluate_and_backpropagate(pending_leaves)
                    pending_leaves = []

        if not root.children:
            legal_moves = list(root_board.legal_moves)
            move = random.choice(legal_moves) if legal_moves else None
            return move, {}

        move_visits = {move: child.N for move, child in root.children.items()}
        total_visits = sum(move_visits.values())

        if total_visits == 0:
            legal_moves = list(root_board.legal_moves)
            move = random.choice(legal_moves) if legal_moves else None
            return move, {}

        move_probs = {m: n / total_visits for m, n in move_visits.items()}
        best_move = max(move_visits.items(), key=lambda kv: kv[1])[0]
        return best_move, move_probs

    def _select(self, root: MCTSNode) -> Tuple[MCTSNode, List[MCTSNode]]:
        node = root
        path = [node]

        while node.is_expanded and (not node.board.is_game_over()):
            # if expanded, it should have children, but be defensive
            if not node.children:
                break
            _, node = self._select_child(node)
            path.append(node)

        return node, path

    def _select_child(self, node: MCTSNode) -> Tuple[chess.Move, MCTSNode]:
        assert node.children, "Tried to select a child from a node with no children."

        N_sum = sum(child.N for child in node.children.values()) + 1e-8

        best_score = -float("inf")
        best_move: Optional[chess.Move] = None
        best_child: Optional[MCTSNode] = None

        for move, child in node.children.items():
            Q = child.Q
            P = node.P.get(move, 0.0)
            U = self.c_puct * P * (math.sqrt(N_sum) / (1.0 + child.N))
            score = Q + U

            if score > best_score:
                best_score = score
                best_move = move
                best_child = child

        # Should always be set given non-empty children
        assert best_move is not None and best_child is not None
        return best_move, best_child

    def _get_terminal_value(self, board: chess.Board) -> float:
        """Get value for terminal board position."""
        result = board.result()  # "1-0", "0-1", "1/2-1/2"
        if result == "1-0":
            return 1.0 if board.turn == chess.WHITE else -1.0
        if result == "0-1":
            return 1.0 if board.turn == chess.BLACK else -1.0
        return 0.0

    def _batch_evaluate_and_backpropagate(self, pending_leaves: List[Tuple[MCTSNode, List[MCTSNode]]]) -> None:
        """Evaluate a batch of leaves and backpropagate results."""
        if not pending_leaves:
            return

        # Prepare batch: convert boards to tensors
        boards = [leaf.board for leaf, _ in pending_leaves]
        board_tensors = []
        for board in boards:
            tensor = board_to_input_planes(board)
            board_tensors.append(tensor)

        # Stack into batch: (batch_size, 18, 8, 8)
        batch_tensor = np.stack(board_tensors)

        # Send inference request with worker_id for routing response
        request_id = str(uuid.uuid4())
        self.inference_queue.put((self.worker_id, batch_tensor, request_id))

        # Block on dedicated response queue (no polling), each process has it's unique queue
        response_request_id, policy_logits_batch, value_batch = self.response_queue.get()

        # Verify we got the right response (should always match with dedicated queues)
        assert response_request_id == request_id, f"Request ID mismatch: {response_request_id} != {request_id}"
        # policy_logits_batch: (batch_size, 4672)
        # value_batch: (batch_size, 1)
        
        # Process each result
        for i, (leaf, path) in enumerate(pending_leaves):
            board = leaf.board
            policy_logits = policy_logits_batch[i]  # (4672,)
            value = float(value_batch[i].squeeze().item())
            
            # Expand node with priors
            legal_moves = list(board.legal_moves)
            legal_moves_dict = {}
            for move in legal_moves:
                move_idx = self.move_indexer.encode(move)
                if move_idx is not None:
                    logit_value = float(policy_logits[move_idx].item())
                    legal_moves_dict[move] = logit_value
            
            # Expand node
            leaf.is_expanded = True
            leaf.P = {}
            leaf.children = {}
            
            # Build children for all legal moves
            for move in board.legal_moves:
                p = float(legal_moves_dict.get(move, 0.0))
                leaf.P[move] = p
                
                child_board = board.copy(stack=False)
                child_board.push(move)
                leaf.children[move] = MCTSNode(child_board, parent=leaf, parent_move=move)
            
            # Renormalize priors over legal moves, fallback to uniform if all 0
            s = sum(leaf.P.values())
            if s > 0.0:
                inv = 1.0 / s
                for m in leaf.P:
                    leaf.P[m] *= inv
            else:
                legal = list(leaf.children.keys())
                if legal:
                    uniform = 1.0 / len(legal)
                    for m in legal:
                        leaf.P[m] = uniform
            
            # Backpropagate
            self._backpropagate(path, value)

    def _backpropagate(self, path: List[MCTSNode], value: float) -> None:
        # value is from the perspective of the side-to-move at the leaf node
        for node in reversed(path):
            node.N += 1
            node.W += value
            node.Q = node.W / node.N
            value = -value  # flip perspective when moving up one ply
    
    # @torch.no_grad()
    # def policy_value_fn(self, board: chess.Board) -> Tuple[Dict[chess.Move, float], float]:
    #     """
    #     Single board evaluation (kept for backward compatibility if needed).
    #     Prefer using batched evaluation via _batch_evaluate_and_backpropagate.
    #     """
    #     board_tensor = board_to_input_planes(board)
    #     board_tensor = torch.from_numpy(board_tensor).unsqueeze(0).to(self.device)
    #     policy_logits, value = self.model(board_tensor)
        
    #     # Remove batch dimension: (1, 4672) -> (4672,)
    #     policy_logits = policy_logits.squeeze(0)
        
    #     legal_moves = list(board.legal_moves)
        
    #     # Map each legal move to its logit value
    #     legal_moves_dict = {}
    #     for move in legal_moves:
    #         move_idx = self.move_indexer.encode(move)
    #         if move_idx is not None:
    #             logit_value = float(policy_logits[move_idx].item())
    #             legal_moves_dict[move] = logit_value
        
    #     return (legal_moves_dict, float(value.squeeze().item()))



if __name__ == "__main__":
    b = chess.Board()
    mcts = MCTS(c_puct=1.5, n_simulations=300)
    move, probs = mcts.search(b)
    # print(move, probs)
    # print(len(probs), len(move))
    print("Best move:", move)
    # print top 10 by probability
    # top = sorted(probs.items(), key=lambda kv: kv[1], reverse=True)[:10]
    # print("Top probs:", top)